import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, test } from 'bun:test'
import { runGenerators } from '../../src/generators/index.js'
import { parseJsonc } from '../../src/lib/jsonc.js'
import { GvKitConfig } from '../../src/schema/config.js'

const repositoryRoot = join(import.meta.dir, '..', '..')
const fixturesDir = join(repositoryRoot, 'fixtures')
const CLOUDFLARE_TYPES_BOOTSTRAP_FILE = 'worker-configuration.bootstrap.d.ts'
const CLOUDFLARE_TYPEGEN_SCRIPT =
	`wrangler types --include-runtime=false && rm -f ${CLOUDFLARE_TYPES_BOOTSTRAP_FILE}`
const WRANGLER_4_125_OWNERSHIP_MARKERS = [
	'Generated by Wrangler',
	'Runtime types generated with workerd'
] as const
const repositoryTopologyGuidance = [
	'AGENTS.md',
	'CLAUDE.md',
	'.claude/rules/service-architecture.md',
	'.claude/rules/api-client.md',
	'.claude/rules/generators.md',
	'README.md',
	'CONTRIBUTING.md',
	'src/generators/services/users.ts'
] as const

function planFixture(name: string) {
	const raw = parseJsonc(readFileSync(join(fixturesDir, `${name}.jsonc`), 'utf8'))
	return runGenerators(GvKitConfig.parse(raw))
}

type CloudflareResponse = Response & {
	readonly cf?: unknown
	readonly webSocket?: WebSocket | null
}
type CloudflareGatewayModule = {
	WorkerdResponse: new (
		body?: unknown,
		init?: ResponseInit & { cf?: unknown; webSocket?: WebSocket | null }
	) => CloudflareResponse
	createGateway(
		targets: { USERS?: { fetch(request: Request): Promise<Response> } },
		options: {
			openApiDocument: {
				openapi: string
				info: Record<string, unknown>
				paths: Record<string, unknown>
			}
			canonicalApiOrigin: string
			corsOrigins: string
			logger: (line: string) => void
		}
	): { fetch(request: Request): Promise<Response> }
}

async function loadWorkerdGatewayContract(): Promise<CloudflareGatewayModule> {
	const app = planFixture('hono-cf-workers-passwordless').find(
		(candidate) => candidate.path === 'apps/api/src/app.ts'
	)
	if (!app) throw new Error('generated Cloudflare gateway app is missing')

	const workerdResponse = `
class WorkerdResponse {
	body
	cf
	headers
	status
	statusText
	webSocket
	constructor(body = null, init = {}) {
		this.body = body
		this.cf = init.cf
		this.headers = new Headers(init.headers)
		this.status = init.status ?? 200
		this.statusText = init.statusText ?? ''
		this.webSocket = init.webSocket ?? null
	}
}
const Response = WorkerdResponse
`
	const honoUrl = import.meta.resolve('hono')
	const source = `${workerdResponse}${app.content.replace("from 'hono'", `from '${honoUrl}'`)}\nexport { WorkerdResponse }`
	const transpiler = new Bun.Transpiler({ loader: 'ts', target: 'bun' })
	const javascript = transpiler.transformSync(source)
	const moduleUrl = URL.createObjectURL(new Blob([javascript], { type: 'text/javascript' }))
	const module = (await import(moduleUrl)) as CloudflareGatewayModule
	URL.revokeObjectURL(moduleUrl)
	return module
}

type Route = { pattern: string; custom_domain?: boolean; zone_name?: string }
type Service = { binding: string; service: string }
type Wrangler = {
	$schema?: string
	name: string
	workers_dev?: boolean
	preview_urls?: boolean
	routes?: Route[]
	services?: Service[]
	vars?: Record<string, string>
	secrets?: { required?: string[] }
	d1_databases?: Array<{ binding: string; database_name: string; database_id: string }>
}

function entry(entries: ReturnType<typeof planFixture>, path: string): string {
	const found = entries.find((candidate) => candidate.path === path)
	if (!found) throw new Error(`Missing generated file: ${path}`)
	return found.content
}

function wrangler(entries: ReturnType<typeof planFixture>, path: string): Wrangler {
	return parseJsonc<Wrangler>(entry(entries, path))
}

describe('Cloudflare gateway production topology', () => {
	test('the workerd gateway keeps platform response state while applying gateway headers', async () => {
		const { createGateway, WorkerdResponse } = await loadWorkerdGatewayContract()
		const webSocket = {} as WebSocket
		const cf = { cacheStatus: 'HIT' }
		const upstream = new WorkerdResponse(null, {
			status: 101,
			headers: { 'access-control-allow-origin': '*' },
			cf,
			webSocket
		})
		const gateway = createGateway(
			{
				USERS: {
					async fetch() {
						return upstream
					}
				}
			},
			{
				openApiDocument: { openapi: '3.0.0', info: {}, paths: {} },
				canonicalApiOrigin: 'https://api.example.test',
				corsOrigins: 'https://app.example.test',
				logger: () => undefined
			}
		)

		const response = (await gateway.fetch(
			new Request('https://api.example.test/api/v1/users/socket', {
				headers: { origin: 'https://app.example.test' }
			})
		)) as CloudflareResponse

		expect(response.status).toBe(101)
		expect(response.webSocket).toBe(webSocket)
		expect(response.cf).toBe(cf)
		expect(response.headers.get('x-request-id')).toMatch(/^[0-9a-f-]{36}$/)
		expect(response.headers.get('access-control-allow-origin')).toBe('https://app.example.test')
	})

	for (const [fixture, webHost] of [
		['hono-cf-workers-passwordless', '<domain>'],
		['astro-cf-workers-full', 'app.<domain>']
	] as const) {
		test(`${fixture} gives only the gateway the API custom domain and web API route`, () => {
			const entries = planFixture(fixture)
			const gateway = wrangler(entries, 'apps/api/wrangler.jsonc')
			const web = wrangler(entries, 'apps/web/wrangler.jsonc')
			const auth = wrangler(entries, 'services/auth/wrangler.jsonc')
			const users = wrangler(entries, 'services/users/wrangler.jsonc')

			expect(gateway.routes).toEqual([
				{ pattern: 'api.<domain>', custom_domain: true },
				{ pattern: `${webHost}/api`, zone_name: '<domain>' },
				{ pattern: `${webHost}/api/*`, zone_name: '<domain>' }
			])
			expect(web.routes).toEqual([{ pattern: webHost, custom_domain: true }])
			expect(auth.routes).toBeUndefined()
			expect(users.routes).toBeUndefined()

			const apiCustomDomains = [gateway, web, auth, users]
				.flatMap((config) => config.routes ?? [])
				.filter((route) => route.custom_domain && route.pattern === 'api.<domain>')
			expect(apiCustomDomains).toHaveLength(1)
		})

		test(`${fixture} keeps services private and exposes only the intended bindings`, () => {
			const entries = planFixture(fixture)
			const gateway = wrangler(entries, 'apps/api/wrangler.jsonc')
			const web = wrangler(entries, 'apps/web/wrangler.jsonc')
			const auth = wrangler(entries, 'services/auth/wrangler.jsonc')
			const users = wrangler(entries, 'services/users/wrangler.jsonc')

			for (const service of [auth, users]) {
				expect(service.workers_dev).toBe(false)
				expect(service.preview_urls).toBe(false)
				expect(service.routes).toBeUndefined()
			}
			expect(web.services).toEqual([
				{ binding: 'GATEWAY', service: `${fixture === 'astro-cf-workers-full' ? 'astro-cf-workers-full' : 'hono-cf-workers-passwordless'}-api` }
			])
			expect(gateway.services).toEqual([
				{ binding: 'AUTH', service: `${gateway.name.replace(/-api$/, '')}-auth` },
				{ binding: 'USERS', service: `${gateway.name.replace(/-api$/, '')}-users` }
			])
			expect(auth.services).toEqual([])
			expect(users.services).toEqual([
				{ binding: 'AUTH', service: `${gateway.name.replace(/-api$/, '')}-auth` }
			])
			if (fixture === 'hono-cf-workers-passwordless') {
				for (const service of [auth, users]) {
					expect(service.d1_databases).toEqual([
						{
							binding: 'DB',
							database_name: 'hono-cf-workers-passwordless-db',
							database_id:
								'<run: wrangler d1 create hono-cf-workers-passwordless-db>'
						}
					])
					expect(service.secrets?.required ?? []).not.toContain('DATABASE_URL')
				}
			} else {
				for (const service of [auth, users]) {
					expect(service.d1_databases).toBeUndefined()
					expect(service.secrets?.required).toContain('DATABASE_URL')
				}
			}
		})
	}

	test('Wrangler can replace clean-install bootstrap types at its default path', () => {
		const entries = planFixture('hono-cf-workers-passwordless')
		const workers = ['apps/api', 'apps/web', 'services/auth', 'services/users'] as const
		for (const directory of workers) {
			expect(wrangler(entries, `${directory}/wrangler.jsonc`).$schema).toBe(
				'node_modules/wrangler/config-schema.json'
			)
			const pkg = JSON.parse(entry(entries, `${directory}/package.json`)) as {
				scripts: Record<string, string>
			}
			expect(pkg.scripts['cf-typegen']).toBe(CLOUDFLARE_TYPEGEN_SCRIPT)
			expect(pkg.scripts.typecheck).not.toContain('cf-typegen')
			expect(
				entries.some((candidate) => candidate.path === `${directory}/worker-configuration.d.ts`)
			).toBe(false)
			const bootstrap = entry(entries, `${directory}/${CLOUDFLARE_TYPES_BOOTSTRAP_FILE}`)
			expect(bootstrap).toContain('Bootstrap bindings derived from wrangler.jsonc')
			expect(bootstrap).toContain('interface Env extends __BaseEnv_Env')
			for (const marker of WRANGLER_4_125_OWNERSHIP_MARKERS) {
				expect(bootstrap).not.toContain(marker)
			}
		}
		expect(entry(entries, 'apps/api/package.json')).toContain(
			'wrangler deploy --dry-run --outdir=dist'
		)
		expect(entry(entries, 'services/auth/package.json')).toContain(
			'wrangler deploy --dry-run --outdir=dist'
		)
		expect(entry(entries, 'services/users/package.json')).toContain(
			'wrangler deploy --dry-run --outdir=dist'
		)
		expect(entries.some((candidate) => candidate.path === 'services/auth/env.d.ts')).toBe(false)
		expect(entries.some((candidate) => candidate.path === 'services/users/env.d.ts')).toBe(false)
		expect(entry(entries, `apps/api/${CLOUDFLARE_TYPES_BOOTSTRAP_FILE}`)).toContain(
			'AUTH: Fetcher'
		)
		expect(entry(entries, `apps/api/${CLOUDFLARE_TYPES_BOOTSTRAP_FILE}`)).toContain(
			'USERS: Fetcher'
		)
		expect(entry(entries, `apps/web/${CLOUDFLARE_TYPES_BOOTSTRAP_FILE}`)).toContain(
			'GATEWAY: Fetcher'
		)
		expect(entry(entries, `services/auth/${CLOUDFLARE_TYPES_BOOTSTRAP_FILE}`)).toContain(
			'DB: D1Database'
		)
		expect(entry(entries, `services/users/${CLOUDFLARE_TYPES_BOOTSTRAP_FILE}`)).toContain(
			'AUTH: Fetcher'
		)
		expect(entry(entries, 'apps/web/src/app.d.ts')).toContain('env: Env')
		expect(entry(entries, 'apps/web/src/app.d.ts')).not.toContain('GATEWAY?: Fetcher')
	})

	test('generated guidance preserves the private gateway topology', () => {
		const entries = planFixture('hono-cf-workers-passwordless')
		const claude = entry(entries, 'CLAUDE.md')
		const serviceArchitect = entry(entries, '.claude/agents/service-architect.md')
		const coreWorkflow = entry(entries, '.ai/rules/core-workflow.md')
		const webRule = entry(entries, '.ai/rules/web-api.md')
		const deployRule = entry(entries, '.ai/rules/deploy-cf-workers.md')
		const completeGuidance = entries
			.filter(
				(candidate) =>
					candidate.path === 'CLAUDE.md' ||
					candidate.path.startsWith('.ai/rules/') ||
					candidate.path.startsWith('.claude/agents/')
			)
			.map((candidate) => candidate.content)
			.join('\n')

		expect(claude).toContain('private workers under `services/`')
		expect(claude).not.toContain('apps/api/<service>')

		expect(serviceArchitect).toContain('services/<svc>/')
		expect(serviceArchitect).toContain('"workers_dev": false')
		expect(serviceArchitect).toContain('"preview_urls": false')
		expect(serviceArchitect).toContain('"secrets": { "required": ["<SECRET_NAME>"] }')
		expect(serviceArchitect).toContain('pnpm cf-typegen')
		expect(serviceArchitect).toContain(
			'never hand-edit either declaration or create a separate `env.d.ts`'
		)
		expect(serviceArchitect).not.toContain('apps/api/<svc>')
		expect(serviceArchitect).not.toContain('Add `AUTH: Fetcher`')

		expect(coreWorkflow).toContain('private Hono Workers under `services/<service>/`')
		expect(coreWorkflow).toContain('`apps/api/` remains the public gateway')
		expect(completeGuidance).not.toContain('Hono Workers under `apps/api/`')

		expect(webRule).toContain("baseUrl: ''")
		expect(webRule).toContain('`GATEWAY` Service Binding')
		expect(webRule).toContain("usersGetMe({ baseUrl: url.origin, fetch })")
		expect(webRule).not.toContain('PUBLIC_USERS_URL')
		expect(webRule).not.toContain('usersFetch')

		expect(deployRule).toContain('platform.env.GATEWAY')
		expect(deployRule).toContain('Browser `/api` and `/api/*` traffic')
		expect(deployRule).toContain('CLOUDFLARE_PREVIEW_WEB_DOMAIN')
		expect(deployRule).toContain('shared proxied wildcard DNS records')
		expect(deployRule).toContain('more-specific web `/api` and `/api/*` routes')
		expect(deployRule).toContain('never shared wildcard DNS')
		expect(deployRule).toContain('services/<service>/wrangler.jsonc')
		expect(deployRule).not.toContain('gateway Service Bindings such as `AUTH`')
		expect(deployRule).not.toContain('apps/api/<service>')
	})

	test('repository-owned topology guidance has no direct-service residue', () => {
		const guidance = repositoryTopologyGuidance
			.map((path) => readFileSync(join(repositoryRoot, path), 'utf8'))
			.join('\n')

		expect(guidance).toContain('`apps/api/` is the only public Hono API application')
		expect(guidance).toContain('`services/<service>/`')
		expect(guidance).toContain('apps/api/openapi.json')
		expect(guidance).toContain('flat `packages/openapi-client`')
		expect(guidance).toContain('`@repo/backend/middleware/auth`')
		expect(guidance).not.toContain('apps/api/<service>')
		expect(guidance).not.toContain('apps/api/auth')
		expect(guidance).not.toContain('apps/api/users')
		expect(guidance).not.toContain('`apps/api` is a container of services')
		expect(guidance).not.toContain('`apps/api` is a CONTAINER')
		expect(guidance).not.toContain('per-service codegen')
		expect(guidance).not.toContain('inline ~10 LOC')
		expect(guidance).not.toContain('local ~10 LOC')
	})

	test('environment examples contain no direct-service public URLs', () => {
		const entries = planFixture('hono-cf-workers-passwordless')
		const local = entry(entries, '.env.example')
		expect(local).not.toMatch(/^PUBLIC_(?:API|AUTH|USERS)_URL=/m)

		const production = entry(entries, '.env.cloudflare.example')
		expect(production).toContain('API_PUBLIC_ORIGIN=https://api.<domain>')
		expect(production).toContain('API_CORS_ORIGINS=https://<domain>')
		expect(production).toContain('GATEWAY_UPSTREAM_TIMEOUT_MS=10000')
		expect(production).toContain('PUBLIC_APP_URL=https://<domain>')
		expect(production).toContain('BETTER_AUTH_ALLOWED_HOSTS=<domain>,api.<domain>')
		expect(production).toContain('AUTH_CORS_ORIGINS=https://<domain>')
		expect(production).not.toMatch(/SECRET|TOKEN|API_KEY|PASSWORD/)

		const gateway = wrangler(entries, 'apps/api/wrangler.jsonc')
		expect(gateway.vars).toEqual({
			API_PUBLIC_ORIGIN: 'https://api.<domain>',
			API_CORS_ORIGINS: 'https://<domain>',
			GATEWAY_UPSTREAM_TIMEOUT_MS: '10000'
		})

		const auth = wrangler(entries, 'services/auth/wrangler.jsonc')
		expect(auth.vars).toEqual({
			BETTER_AUTH_ALLOWED_HOSTS: '<domain>,api.<domain>',
			AUTH_CORS_ORIGINS: 'https://<domain>'
		})
	})

	test('gateway, web, auth, and users expose affected build and deploy tasks', () => {
		const entries = planFixture('hono-cf-workers-passwordless')
		for (const path of [
			'apps/api/package.json',
			'apps/web/package.json',
			'services/auth/package.json',
			'services/users/package.json'
		]) {
			const pkg = JSON.parse(entry(entries, path)) as { scripts: Record<string, string> }
			expect(pkg.scripts.build, path).toBeDefined()
			expect(pkg.scripts['deploy:production'], path).toContain('wrangler deploy')
			expect(pkg.scripts['deploy:staging'], path).toContain('wrangler deploy')
		}
	})

	test('Cloudflare-only files do not leak into non-Cloudflare or inside-frontend output', () => {
		const docker = planFixture('hono-docker-full')
		expect(docker.some((candidate) => candidate.path === '.env.cloudflare.example')).toBe(false)
		expect(docker.some((candidate) => candidate.path === 'apps/api/wrangler.jsonc')).toBe(false)

		const integrated = planFixture('inside-frontend-typical')
		expect(integrated.some((candidate) => candidate.path === '.env.cloudflare.example')).toBe(false)
		expect(integrated.some((candidate) => candidate.path === 'apps/api/wrangler.jsonc')).toBe(false)
		expect(integrated.some((candidate) => candidate.path.startsWith('services/'))).toBe(false)
		const integratedWeb = wrangler(integrated, 'apps/web/wrangler.jsonc')
		expect(integratedWeb.$schema).toBe('https://unpkg.com/wrangler@latest/config-schema.json')
		expect(integratedWeb.workers_dev).toBeUndefined()
		expect(integratedWeb.preview_urls).toBeUndefined()
		const integratedPackage = JSON.parse(entry(integrated, 'apps/web/package.json')) as {
			scripts: Record<string, string>
		}
		expect(integratedPackage.scripts['cf-typegen']).toBeUndefined()
		expect(entry(integrated, 'apps/web/src/app.d.ts')).toContain('env: {\n\t\t\t}')
	})
})
