#!/usr/bin/env bun
/**
 * Walks fixtures/templates/{root,web,ui,marketing}/{base,overlays/*,package.json.fragments/*}
 * and emits src/generated/<tree>-templates.ts with a frozen Record<string, string>.
 *
 * Run: bun run bundle:templates
 * CI:  bun run bundle:templates -- --check
 */
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { join, posix, relative, resolve, sep } from 'node:path'

const REPO_ROOT = resolve(import.meta.dir, '..')
const TEMPLATES_ROOT = join(REPO_ROOT, 'fixtures', 'templates')
const OUTPUT_DIR = join(REPO_ROOT, 'src', 'generated')

const TREES = ['root', 'web', 'ui', 'marketing'] as const
type Tree = (typeof TREES)[number]

const SKIP_FILES = new Set(['.DS_Store'])
const SKIP_DIRS = new Set(['node_modules', '.svelte-kit', 'build', 'dist', '.wrangler'])

function main(): void {
	const checkMode = process.argv.includes('--check')

	for (const tree of TREES) {
		const record = bundleTree(tree)
		const source = renderModule(tree, record)
		const outPath = join(OUTPUT_DIR, `${tree}-templates.ts`)

		if (checkMode) {
			let existing = ''
			try {
				existing = readFileSync(outPath, 'utf8')
			} catch {
				existing = ''
			}
			if (existing !== source) {
				console.error(
					`bundle-templates: drift detected in ${posix.join('src/generated', `${tree}-templates.ts`)}`
				)
				console.error("bundle-templates: run 'bun run bundle:templates' and commit the result.")
				process.exit(1)
			}
		} else {
			writeFileSync(outPath, source)
			console.log(
				`bundle-templates: wrote src/generated/${tree}-templates.ts (${Object.keys(record).length} files)`
			)
		}
	}
}

function bundleTree(tree: Tree): Record<string, string> {
	const root = join(TEMPLATES_ROOT, tree)
	const out: Record<string, string> = {}

	walk(root, root, (absPath, relPath) => {
		out[toPosix(relPath)] = readFileSync(absPath, 'utf8')
	})

	const sorted: Record<string, string> = {}
	for (const key of Object.keys(out).sort()) sorted[key] = out[key]!
	return sorted
}

function walk(dir: string, root: string, visit: (absPath: string, relPath: string) => void): void {
	let entries: string[]
	try {
		entries = readdirSync(dir)
	} catch {
		return
	}
	entries.sort()
	for (const name of entries) {
		if (SKIP_FILES.has(name)) continue
		const abs = join(dir, name)
		let st
		try {
			st = statSync(abs)
		} catch {
			continue
		}
		if (st.isDirectory()) {
			if (SKIP_DIRS.has(name)) continue
			walk(abs, root, visit)
		} else if (st.isFile()) {
			visit(abs, relative(root, abs))
		}
	}
}

function toPosix(p: string): string {
	return sep === '/' ? p : p.split(sep).join('/')
}

function renderModule(tree: Tree, record: Record<string, string>): string {
	const exportName = `${tree}Templates`
	const banner = [
		'// AUTO-GENERATED by scripts/bundle-templates.ts. DO NOT EDIT BY HAND.',
		'// Regenerate with: bun run bundle:templates',
		`// Fixture source: fixtures/templates/${tree}/`,
		''
	].join('\n')

	const keys = Object.keys(record)
	if (keys.length === 0) {
		return `${banner}\nexport const ${exportName}: Record<string, string> = {}\n`
	}

	const body = keys
		.map((key) => {
			const value = record[key]!
			return `\t${quoteKey(key)}: ${stringLiteral(value)}`
		})
		.join(',\n')

	return `${banner}\nexport const ${exportName}: Record<string, string> = {\n${body}\n}\n`
}

function quoteKey(key: string): string {
	return JSON.stringify(key)
}

function stringLiteral(value: string): string {
	return JSON.stringify(value)
}

main()
