import { spawn } from 'node:child_process'
import { access, mkdir, readFile, rm, writeFile } from 'node:fs/promises'
import { join, resolve } from 'node:path'
import {
	CLOUDFLARE_TYPEGEN_SCRIPT,
	CLOUDFLARE_TYPES_BOOTSTRAP_FILE
} from '../src/generators/cloudflare-worker-types.js'
import { parseJsonc } from '../src/lib/jsonc.js'
import { buildScaffoldPlan } from '../src/pipeline/plan.js'
import { GvKitConfig, type GvKitConfig as Config } from '../src/schema/config.js'
import {
	appendCommandEvidence,
	assertPermittedWranglerInvocation,
	writeSanitizedArtifact
} from './gateway-verification-evidence.js'

const PNPM_VERSION = '11.1.1'
const CORE_WORKERS = [
	{ name: 'gateway', directory: 'apps/api' },
	{ name: 'web', directory: 'apps/web' },
	{ name: 'auth', directory: 'services/auth' },
	{ name: 'users', directory: 'services/users' }
] as const
const MARKETING_WORKER = { name: 'marketing', directory: 'apps/marketing' } as const
const WRANGLER_4_125_OWNERSHIP_MARKERS = [
	'Generated by Wrangler',
	'Runtime types generated with workerd'
] as const

type WorkerName = (typeof CORE_WORKERS)[number]['name'] | typeof MARKETING_WORKER.name
type WorkerTarget = { name: WorkerName; directory: string }
type WranglerConfigs = Record<WorkerName, WranglerConfig>

type WranglerConfig = {
	name: string
	workers_dev?: boolean
	preview_urls?: boolean
	routes?: Array<{ pattern: string; custom_domain?: boolean; zone_name?: string }>
	services?: Array<{ binding: string; service: string }>
	vars?: Record<string, string>
	secrets?: { required?: string[] }
	d1_databases?: Array<{ binding: string; database_name: string; database_id: string }>
	assets?: { binding?: string }
}

type CommandResult = {
	command: string
	output: string
	outcome: 'passed'
	durationMs: number
	logPath: string
	exitCode: number
}

type CloudflareCommandOptions = {
	name: string
	executable: string
	args: string[]
	cwd: string
	logPath: string
	extraEnv?: Record<string, string>
}

function parseArgs(argv: string[]): { fixture: string; output: string; stagingAlias: string } {
	let fixture = 'hono-cf-workers-passwordless'
	let output = resolve('.scratch/gateway-cloudflare')
	let stagingAlias = 'pr-123'
	for (let index = 0; index < argv.length; index += 1) {
		const arg = argv[index]
		if (arg === '--fixture') fixture = argv[++index] ?? fixture
		else if (arg === '--output') output = resolve(argv[++index] ?? output)
		else if (arg === '--staging-alias') stagingAlias = argv[++index] ?? stagingAlias
		else throw new Error(`Unknown argument: ${arg}`)
	}
	if (!/^pr-[1-9][0-9]*$/.test(stagingAlias) || stagingAlias.length > 48)
		throw new Error('--staging-alias must be a canonical bounded Cloudflare preview alias')
	return { fixture, output, stagingAlias }
}

async function assertRejectedPreviewAlias({
	project,
	alias
}: {
	project: string
	alias: string
}): Promise<{ alias: string; rejected: true }> {
	const child = spawn('node', ['scripts/cloudflare-preview-name.mjs', '--validate', alias], {
		cwd: project,
		stdio: ['ignore', 'pipe', 'pipe']
	})
	let output = ''
	child.stdout.on('data', (chunk) => (output += chunk.toString()))
	child.stderr.on('data', (chunk) => (output += chunk.toString()))
	const code = await new Promise<number>((done, reject) => {
		child.on('error', reject)
		child.on('close', (status) => done(status ?? 1))
	})
	if (code === 0) throw new Error(`unsafe preview alias was accepted: ${alias}`)
	if (!/Preview alias/.test(output)) throw new Error(`preview alias rejection was not explicit: ${alias}`)
	return { alias, rejected: true }
}

async function run({
	name,
	executable,
	args,
	cwd,
	logPath,
	extraEnv = {}
}: CloudflareCommandOptions): Promise<CommandResult> {
	const started = performance.now()
	assertPermittedWranglerInvocation(args)
	const child = spawn(executable, args, {
		cwd,
		env: {
			...process.env,
			CI: '1',
			PUBLIC_TURNSTILE_SITE_KEY: '1x00000000000000000000AA',
			WRANGLER_SEND_METRICS: 'false',
			PATH: `${join(cwd, '.verify-bin')}:${process.env.PATH ?? ''}`,
			...extraEnv
		},
		stdio: ['ignore', 'pipe', 'pipe']
	})
	let output = ''
	child.stdout.on('data', (chunk) => (output += chunk.toString()))
	child.stderr.on('data', (chunk) => (output += chunk.toString()))
	const code = await new Promise<number>((done, reject) => {
		child.on('error', reject)
		child.on('close', (status) => done(status ?? 1))
	})
	const renderedCommand = `${executable} ${args.join(' ')}`
	await writeSanitizedArtifact({
		path: logPath,
		content: `$ ${renderedCommand}\n\n${output}`,
		roots: [cwd]
	})
	const record = {
		name,
		command: renderedCommand,
		outcome: code === 0 ? ('passed' as const) : ('failed' as const),
		durationMs: Math.round(performance.now() - started),
		logPath,
		exitCode: code
	}
	await appendCommandEvidence(cwd, record)
	if (code !== 0) throw new Error(`${renderedCommand} failed; see ${logPath}`)
	return { ...record, outcome: 'passed', output }
}

async function materialize(
	fixture: string,
	output: string
): Promise<{ config: Config; project: string }> {
	const config = GvKitConfig.parse(
		parseJsonc(await readFile(resolve('fixtures', `${fixture}.jsonc`), 'utf8'))
	)
	if (config.choices.backend !== 'hono') throw new Error(`${fixture} is not a Hono fixture`)
	if (config.choices.deploy !== 'cf-workers')
		throw new Error(`${fixture} does not use deploy: cf-workers`)

	const project = join(output, fixture)
	await rm(project, { recursive: true, force: true })
	await mkdir(project, { recursive: true })
	for (const file of buildScaffoldPlan(config)) {
		const target = join(project, file.path)
		await mkdir(resolve(target, '..'), { recursive: true })
		await writeFile(target, file.content, { encoding: 'utf8', mode: file.mode })
	}
	const binPath = join(project, '.verify-bin')
	await mkdir(binPath, { recursive: true })
	await writeFile(join(binPath, 'pnpm'), `#!/bin/sh\nexec corepack pnpm@${PNPM_VERSION} "$@"\n`, {
		mode: 0o755
	})
	return { config, project }
}

async function readWrangler({
	project,
	directory,
	file = 'wrangler.jsonc'
}: {
	project: string
	directory: string
	file?: string
}): Promise<WranglerConfig> {
	return parseJsonc(await readFile(join(project, directory, file), 'utf8'))
}

function inventory(config: WranglerConfig) {
	return {
		name: config.name,
		routes: config.routes ?? [],
		services: config.services ?? [],
		workersDev: config.workers_dev ?? true,
		previewUrls: config.preview_urls ?? config.workers_dev ?? true,
		vars: Object.keys(config.vars ?? {}).sort(),
		requiredSecrets: [...(config.secrets?.required ?? [])].sort(),
		d1Databases: config.d1_databases ?? []
	}
}

function assertTopology(configs: WranglerConfigs): void {
	const canonical = configs.gateway.routes?.filter(
		(route) => route.custom_domain && route.pattern === 'api.<domain>'
	)
	if (canonical?.length !== 1) throw new Error('gateway does not own exactly one API Custom Domain')
	if (!configs.gateway.routes?.some((route) => route.pattern.endsWith('/api')))
		throw new Error('gateway does not own the exact web-origin /api route')
	if (!configs.gateway.routes?.some((route) => route.pattern.endsWith('/api/*')))
		throw new Error('gateway does not own the web-origin /api/* route')
	for (const name of ['auth', 'users'] as const) {
		const config = configs[name]
		if (config.routes !== undefined) throw new Error(`${name} unexpectedly has a public route`)
		if (config.workers_dev !== false) throw new Error(`${name} enables workers.dev`)
		if (config.preview_urls !== false) throw new Error(`${name} enables production preview URLs`)
	}
	if (configs.web.services?.map(({ binding }) => binding).join(',') !== 'GATEWAY')
		throw new Error('web has bindings other than GATEWAY')
	if (configs.gateway.services?.map(({ binding }) => binding).join(',') !== 'AUTH,USERS')
		throw new Error('gateway does not bind exactly AUTH and USERS')
	if (configs.users.services?.map(({ binding }) => binding).join(',') !== 'AUTH')
		throw new Error('users does not bind exactly AUTH')
	if ((configs.auth.services ?? []).length !== 0) throw new Error('auth has a service binding')
}

function assertPreviewTopology({
	preview,
	workers,
	alias,
	apiOrigin,
	webOrigin,
	marketingOrigin,
	zoneName
}: {
	preview: WranglerConfigs
	workers: WorkerTarget[]
	alias: string
	apiOrigin: string
	webOrigin: string
	marketingOrigin?: string | undefined
	zoneName: string
}): void {
	for (const worker of workers) {
		const config = preview[worker.name]
		if (!config.name.endsWith(`-${alias}`))
			throw new Error(`${worker.name} does not use the preview alias`)
		if (config.name.length > 63) throw new Error(`${worker.name} exceeds the Worker name limit`)
		if (config.preview_urls !== false) throw new Error(`${worker.name} enables preview URLs`)
		if (config.workers_dev !== false) throw new Error(`${worker.name} exposes workers.dev`)
	}
	for (const name of ['auth', 'users'] as const) {
		if (preview[name].routes !== undefined) throw new Error(`${name} has a public preview route`)
	}
	const expectedRoutes: Partial<Record<WorkerName, WranglerConfig['routes']>> = {
		gateway: [
			{ pattern: `${new URL(apiOrigin).host}/*`, zone_name: zoneName },
			{ pattern: `${new URL(webOrigin).host}/api`, zone_name: zoneName },
			{ pattern: `${new URL(webOrigin).host}/api/*`, zone_name: zoneName }
		],
		web: [{ pattern: `${new URL(webOrigin).host}/*`, zone_name: zoneName }],
		...(marketingOrigin
			? {
					marketing: [{ pattern: `${new URL(marketingOrigin).host}/*`, zone_name: zoneName }]
				}
			: {})
	}
	const publicWorkerNames: WorkerName[] = [
		'gateway',
		'web',
		...(marketingOrigin ? (['marketing'] as const) : [])
	]
	for (const name of publicWorkerNames) {
		if (JSON.stringify(preview[name].routes) !== JSON.stringify(expectedRoutes[name]))
			throw new Error(`${name} preview routes do not preserve direct managed ingress`)
	}
	const expectedServices = {
		gateway: [
			{ binding: 'AUTH', service: preview.auth.name },
			{ binding: 'USERS', service: preview.users.name }
		],
		web: [{ binding: 'GATEWAY', service: preview.gateway.name }],
		users: [{ binding: 'AUTH', service: preview.auth.name }]
	}
	for (const name of ['gateway', 'web', 'users'] as const) {
		if (JSON.stringify(preview[name].services) !== JSON.stringify(expectedServices[name]))
			throw new Error(`${name} preview Service Bindings are not isolated`)
	}
	if (preview.gateway.vars?.API_PUBLIC_ORIGIN !== apiOrigin)
		throw new Error('gateway preview OpenAPI origin is not explicit')
	const localHosts = 'localhost:3000,localhost:5173,localhost:8786,127.0.0.1:8786'
	const localOrigins =
		'http://localhost:3000,http://localhost:5173,http://localhost:8786,http://127.0.0.1:8786'
	if (
		preview.gateway.vars?.GATEWAY_PUBLIC_ORIGINS !==
		`${webOrigin},${apiOrigin},${localOrigins}`
	)
		throw new Error('gateway preview public-origin allowlist contains the wrong origins')
	if (preview.gateway.vars?.API_CORS_ORIGINS !== `${webOrigin},${localOrigins}`)
		throw new Error('gateway preview CORS contains the wrong origins')
	if (preview.gateway.vars?.GATEWAY_UPSTREAM_TIMEOUT_MS !== '10000')
		throw new Error('gateway preview timeout is not explicit')
	if (
		preview.auth.vars?.BETTER_AUTH_ALLOWED_HOSTS !==
		`${new URL(webOrigin).host},${new URL(apiOrigin).host},${localHosts}`
	)
		throw new Error('auth preview allowed hosts contain the wrong origins')
	if (preview.auth.vars?.AUTH_CORS_ORIGINS !== `${webOrigin},${apiOrigin},${localOrigins}`)
		throw new Error('auth preview CORS contains the wrong origins')
}

type DatabaseEvidence =
	| {
			kind: 'd1'
			previewDatabaseName: string
			previewDatabaseId: string
			productionDatabaseNames: string[]
	  }
	| {
			kind: 'neon'
			previewBranchName: string
			previewDatabaseUrlRedacted: true
			privateWorkers: string[]
	  }

function assertPreviewDatabaseIsolation({
	config,
	production,
	preview,
	alias,
	previewDatabaseName,
	previewDatabaseId,
	previewDatabaseUrl,
	previewSecretValues
}: {
	config: Config
	production: WranglerConfigs
	preview: WranglerConfigs
	alias: string
	previewDatabaseName: string
	previewDatabaseId: string
	previewDatabaseUrl: string
	previewSecretValues: Partial<Record<'auth' | 'users', Record<string, string>>>
}): DatabaseEvidence {
	const privateWorkers = ['auth', 'users'] as const
	if (config.choices.db === 'sqlite') {
		const productionDatabases = privateWorkers.flatMap(
			(name) => production[name].d1_databases?.filter(({ binding }) => binding === 'DB') ?? []
		)
		for (const name of privateWorkers) {
			const databases = preview[name].d1_databases?.filter(({ binding }) => binding === 'DB') ?? []
			if (
				databases.length !== 1 ||
				databases[0]?.database_name !== previewDatabaseName ||
				databases[0]?.database_id !== previewDatabaseId
			)
				throw new Error(`${name} preview D1 binding is not isolated`)
			if (preview[name].secrets?.required?.includes('DATABASE_URL'))
				throw new Error(`${name} D1 preview unexpectedly requires DATABASE_URL`)
		}
		if (
			productionDatabases.length !== 2 ||
			productionDatabases.some(
				(database) =>
					database.database_name === previewDatabaseName ||
					database.database_id === previewDatabaseId
			)
		)
			throw new Error('production and preview D1 bindings are not distinct')
		if (Object.values(previewSecretValues).some((values) => values?.DATABASE_URL))
			throw new Error('D1 preview secret files contain DATABASE_URL')
		return {
			kind: 'd1',
			previewDatabaseName,
			previewDatabaseId,
			productionDatabaseNames: productionDatabases.map(({ database_name }) => database_name)
		}
	}
	for (const name of privateWorkers) {
		if (
			(production[name].d1_databases?.length ?? 0) > 0 ||
			(preview[name].d1_databases?.length ?? 0) > 0
		)
			throw new Error(`${name} PostgreSQL topology unexpectedly has D1 bindings`)
		if (!preview[name].secrets?.required?.includes('DATABASE_URL'))
			throw new Error(`${name} Neon preview does not require DATABASE_URL`)
		if (previewSecretValues[name]?.DATABASE_URL !== previewDatabaseUrl)
			throw new Error(`${name} preview secrets do not contain the isolated Neon URL`)
	}
	return {
		kind: 'neon',
		previewBranchName: `${config.choices.name}-db-${alias}`,
		previewDatabaseUrlRedacted: true,
		privateWorkers: [...privateWorkers]
	}
}

function verificationSecretValue(name: string): string {
	switch (name) {
		case 'DATABASE_URL':
			return 'postgres://verify:verify@localhost:5432/verify'
		case 'FROM_EMAIL':
			return 'verify@example.test'
		case 'NOTIFUSE_BASE_URL':
			return 'https://notifuse.example.test'
		case 'BETTER_AUTH_SECRET':
			return 'verification-only-better-auth-secret-32-characters'
		default:
			return `verification-only-${name.toLowerCase().replaceAll('_', '-')}`
	}
}

async function assertPreviewDeployScripts(
	project: string,
	workers: WorkerTarget[]
): Promise<Record<string, string>> {
	const commands: Record<string, string> = {}
	for (const worker of workers) {
		const packageJson = JSON.parse(
			await readFile(join(project, worker.directory, 'package.json'), 'utf8')
		) as { scripts?: Record<string, string> }
		const command = packageJson.scripts?.['deploy:staging']
		if (!command?.includes('wrangler deploy --config'))
			throw new Error(`${worker.name} staging deploy does not use its prepared config`)
		if (command.includes('--name'))
			throw new Error(`${worker.name} staging deploy overrides its prepared config name`)
		commands[worker.name] = command
	}
	return commands
}

async function generatedInputSnapshot(
	project: string,
	workers: WorkerTarget[]
): Promise<Record<string, string>> {
	const paths = workers.flatMap((worker) => [
		join(worker.directory, 'package.json'),
		...(worker.name === 'marketing'
			? []
			: [join(worker.directory, CLOUDFLARE_TYPES_BOOTSTRAP_FILE)])
	])
	return Object.fromEntries(
		(
			await Promise.all(
				paths.map(async (path) => [path, await readFile(join(project, path), 'utf8')] as const)
			)
		).sort(([left], [right]) => left.localeCompare(right))
	)
}

async function assertTypegenContract(project: string): Promise<Record<string, string[]>> {
	const expected: Record<string, string[]> = {
		gateway: [
			'AUTH',
			'USERS',
			'API_PUBLIC_ORIGIN',
			'GATEWAY_PUBLIC_ORIGINS',
			'API_CORS_ORIGINS',
			'GATEWAY_UPSTREAM_TIMEOUT_MS'
		],
		web: ['GATEWAY'],
		auth: ['BETTER_AUTH_SECRET', 'BETTER_AUTH_ALLOWED_HOSTS', 'AUTH_CORS_ORIGINS'],
		users: ['AUTH']
	}
	for (const worker of CORE_WORKERS) {
		const defaultTypesPath = join(project, worker.directory, 'worker-configuration.d.ts')
		if (
			await access(defaultTypesPath)
				.then(() => true)
				.catch(() => false)
		)
			throw new Error(`${worker.name} bootstrap occupies Wrangler's default output path`)
		const bootstrap = await readFile(
			join(project, worker.directory, CLOUDFLARE_TYPES_BOOTSTRAP_FILE),
			'utf8'
		)
		for (const marker of WRANGLER_4_125_OWNERSHIP_MARKERS) {
			if (bootstrap.includes(marker))
				throw new Error(`${worker.name} bootstrap claims Wrangler ownership with ${marker}`)
		}
		for (const binding of expected[worker.name] ?? []) {
			if (!bootstrap.includes(binding))
				throw new Error(`${worker.name} bootstrap types omit ${binding}`)
		}
		const packageJson = JSON.parse(
			await readFile(join(project, worker.directory, 'package.json'), 'utf8')
		) as { scripts?: Record<string, string> }
		if (packageJson.scripts?.['cf-typegen'] !== CLOUDFLARE_TYPEGEN_SCRIPT)
			throw new Error(`${worker.name} typegen does not replace the bootstrap with Wrangler output`)
	}
	return expected
}

async function main(): Promise<void> {
	const args = parseArgs(process.argv.slice(2))
	const { config, project } = await materialize(args.fixture, args.output)
	const hasMarketing = await access(join(project, MARKETING_WORKER.directory, 'wrangler.jsonc'))
		.then(() => true)
		.catch(() => false)
	const workers: WorkerTarget[] = [...CORE_WORKERS, ...(hasMarketing ? [MARKETING_WORKER] : [])]
	console.log(`[gateway-cloudflare] generated project: ${project}`)
	const generatedInputs = await generatedInputSnapshot(project, workers)
	const webHooks = await readFile(join(project, 'apps/web/src/hooks.server.ts'), 'utf8')
	if (webHooks.includes('forwardApiAlias') || webHooks.includes('gateway.fetch(event.request)'))
		throw new Error('generated SvelteKit hooks contain an inbound browser API proxy')
	if (!webHooks.includes('export const handleFetch'))
		throw new Error('generated SvelteKit hooks omit the private SSR gateway transport')

	await run({
		name: 'install',
		executable: 'corepack',
		args: [`pnpm@${PNPM_VERSION}`, 'install', '--no-frozen-lockfile'],
		cwd: project,
		logPath: join(project, 'install.log')
	})

	const workspaceChecks: CommandResult[] = []
	const workspacePublicEnv = hasMarketing
		? {
				PUBLIC_MARKETING_URL: 'https://marketing.preview-verification.example',
				PUBLIC_APP_URL: 'https://app.preview-verification.example'
			}
		: {}
	for (const task of ['lint', 'typecheck', 'test', 'build']) {
		workspaceChecks.push(
			await run({
				name: `workspace-${task}`,
				executable: 'corepack',
				args: [`pnpm@${PNPM_VERSION}`, task],
				cwd: project,
				logPath: join(project, `${task}.log`),
				extraEnv: workspacePublicEnv
			})
		)
	}
	if (
		JSON.stringify(await generatedInputSnapshot(project, workers)) !==
		JSON.stringify(generatedInputs)
	)
		throw new Error(
			'normal workspace gates modified generated package scripts or binding declarations'
		)

	const configs = Object.fromEntries(
		await Promise.all(
			workers.map(async (worker) => [
				worker.name,
				await readWrangler({ project, directory: worker.directory })
			])
		)
	) as WranglerConfigs
	assertTopology(configs)
	const generatedTypes = await assertTypegenContract(project)
	const previewDeployScripts = await assertPreviewDeployScripts(project, workers)

	const dryRuns: Record<string, { command: string; output: string }> = {}
	for (const worker of workers) {
		const result = await run({
			name: `production-wrangler-dry-run-${worker.name}`,
			executable: 'corepack',
			args: [
				`pnpm@${PNPM_VERSION}`,
				'--dir',
				worker.directory,
				'exec',
				'wrangler',
				'deploy',
				'--dry-run',
				'--outdir',
				'.wrangler/verify-dry-run'
			],
			cwd: project,
			logPath: join(project, `wrangler-${worker.name}-dry-run.log`)
		})
		dryRuns[worker.name] = result
	}

	const stagingWorkflow = await readFile(
		join(project, '.github/workflows/deploy-staging.yml'),
		'utf8'
	)
	const cleanupWorkflow = await readFile(
		join(project, '.github/workflows/cleanup-staging.yml'),
		'utf8'
	)
	if (
		!stagingWorkflow.includes('preview-db:\n    needs: preview-ingress') ||
		stagingWorkflow.indexOf('preview-ingress:') > stagingWorkflow.indexOf('preview-db:') ||
		!stagingWorkflow.includes('node scripts/verify-cloudflare-preview-ingress.mjs')
	)
		throw new Error('managed preview ingress is not verified before database provisioning')
	for (const marker of [
		'workflow_dispatch:',
		'alias:',
		'required: true',
		'ref: ${{ github.event.repository.default_branch }}',
		'node scripts/cloudflare-preview-name.mjs --validate "$RAW_PREVIEW_ALIAS"',
		'sh scripts/cleanup-cloudflare-preview-workers.sh "${{ steps.alias.outputs.alias }}"'
	]) {
		if (!cleanupWorkflow.includes(marker))
			throw new Error(`preview cleanup lifecycle omits ${marker}`)
	}
	if (
		cleanupWorkflow.includes('github.event.pull_request.head.sha') ||
		cleanupWorkflow.includes('github.event.pull_request.base.sha')
	)
		throw new Error('preview cleanup checks out PR-controlled code')
	if (!stagingWorkflow.includes('gh workflow run cleanup-staging.yml -f alias=$alias'))
		throw new Error('manual previews do not report their deterministic cleanup invocation')
	if (
		stagingWorkflow.indexOf('gh workflow run cleanup-staging.yml') >
		stagingWorkflow.indexOf('Create or reuse')
	)
		throw new Error('preview cleanup invocation is reported after resource provisioning starts')
	if (config.choices.auth.includes('emailOTP')) {
		for (const marker of [
			'#   - PUBLIC_TURNSTILE_SITE_KEY',
			'test -n "$PUBLIC_TURNSTILE_SITE_KEY"',
			'PUBLIC_TURNSTILE_SITE_KEY: ${{ vars.PUBLIC_TURNSTILE_SITE_KEY }}'
		]) {
			if (!stagingWorkflow.includes(marker))
				throw new Error(`email-OTP preview Turnstile contract omits ${marker}`)
		}
		if (
			stagingWorkflow.indexOf('Validate preview public variables') >
			stagingWorkflow.indexOf('preview-db:')
		)
			throw new Error('email-OTP preview validates Turnstile after resource provisioning starts')
	}
	const cleanupScript = await readFile(
		join(project, 'scripts/cleanup-cloudflare-preview-workers.sh'),
		'utf8'
	)
	for (const marker of [
		'find "$@" -name wrangler.jsonc',
		'node scripts/cloudflare-preview-name.mjs "$base_name" "$alias"',
		'npx wrangler@4.125.0 delete --name "$worker_name" --force',
		'Shared wildcard DNS records'
	]) {
		if (!cleanupScript.includes(marker)) throw new Error(`preview cleanup inventory omits ${marker}`)
	}
	if (/dns_records|api\.cloudflare\.com|wrangler[^\n]*dns/i.test(cleanupScript))
		throw new Error('preview cleanup can delete shared wildcard DNS')

	const manualAliasResult = await run({
		name: 'derive-manual-preview-alias',
		executable: 'node',
		args: ['scripts/cloudflare-preview-name.mjs', '--from-id', '987654321'],
		cwd: project,
		logPath: join(project, 'derive-manual-preview-alias.log')
	})
	const manualAlias = manualAliasResult.output.trim()
	if (manualAlias !== 'pr-987654321') throw new Error('manual preview alias is not canonical')
	const rejectedAliases = await Promise.all(
		['production', 'demo-api', 'pr-0', `pr-${'1'.repeat(46)}`].map((alias) =>
			assertRejectedPreviewAlias({ project, alias })
		)
	)

	const ingressPrerequisiteScript = await readFile(
		join(project, 'scripts/verify-cloudflare-preview-ingress.mjs'),
		'utf8'
	)
	for (const marker of [
		"cloudflare('/zones?name='",
		"'/dns_records?name='",
		'record.proxied === true',
		"wildcard = '*.' + parent"
	]) {
		if (!ingressPrerequisiteScript.includes(marker))
			throw new Error(`managed preview ingress prerequisite script omits ${marker}`)
	}

	const failClosed = await run({
		name: 'preview-managed-domains-fail-closed',
		executable: 'sh',
		args: [
			'-c',
			`set -eu
output=.wrangler/preview-managed-domains-blocked.log
mkdir -p .wrangler
if node scripts/prepare-cloudflare-preview.mjs >"$output" 2>&1; then
	echo "preview preparation unexpectedly succeeded without managed domains" >&2
	exit 1
fi
grep -F "CLOUDFLARE_PREVIEW_ZONE_NAME is required" "$output"
for config in apps/api apps/web services/auth services/users; do
	test ! -e "$config/wrangler.staging.jsonc"
done
cat "$output"`
		],
		cwd: project,
		logPath: join(project, 'preview-managed-domains-blocked.log'),
		extraEnv: { STAGING_ALIAS: args.stagingAlias }
	})

	const previewZoneName = 'preview-verification.example'
	const previewWebDomain = `app.${previewZoneName}`
	const previewApiDomain = `api.${previewZoneName}`
	const previewDatabaseName = `${configs.auth.name.replace(/-auth$/, '-db')}-${args.stagingAlias}`
	const previewDatabaseId = '11111111-1111-4111-8111-111111111111'
	const previewDatabaseUrl =
		'postgres://preview:preview@preview-verification.example.test:5432/preview'
	const previewPreparation = await run({
		name: 'prepare-preview-configs',
		executable: 'node',
		args: ['scripts/prepare-cloudflare-preview.mjs'],
		cwd: project,
		logPath: join(project, 'prepare-cloudflare-preview.log'),
		extraEnv: {
			STAGING_ALIAS: args.stagingAlias,
			PREVIEW_DB_KIND: config.choices.db === 'sqlite' ? 'd1' : 'neon',
			...(config.choices.db === 'sqlite'
				? {
						STAGING_D1_DATABASE_NAME: previewDatabaseName,
						STAGING_D1_DATABASE_ID: previewDatabaseId
					}
				: { STAGING_DATABASE_URL: previewDatabaseUrl }),
			CLOUDFLARE_PREVIEW_WEB_DOMAIN: previewWebDomain,
			CLOUDFLARE_PREVIEW_API_DOMAIN: previewApiDomain,
			CLOUDFLARE_PREVIEW_ZONE_NAME: previewZoneName
		}
	})
	const previewConfigs = Object.fromEntries(
		await Promise.all(
			workers.map(async (worker) => [
				worker.name,
				await readWrangler({
					project,
					directory: worker.directory,
					file: 'wrangler.staging.jsonc'
				})
			])
		)
	) as WranglerConfigs
	const apiOrigin = `https://${args.stagingAlias}.${previewApiDomain}`
	const webOrigin = `https://${args.stagingAlias}.${previewWebDomain}`
	const marketingOrigin = hasMarketing
		? `https://${args.stagingAlias}-marketing.${previewWebDomain}`
		: undefined
	if (
		marketingOrigin &&
		!previewPreparation.output.includes(`"marketingOrigin": "${marketingOrigin}"`)
	)
		throw new Error('marketing preview origin does not use the managed web domain')
	assertPreviewTopology({
		preview: previewConfigs,
		workers,
		alias: args.stagingAlias,
		apiOrigin,
		webOrigin,
		marketingOrigin,
		zoneName: previewZoneName
	})

	const previewSecretDirectory = join(project, '.wrangler/verify-preview-secrets')
	const requiredPreviewSecrets = {
		auth: previewConfigs.auth.secrets?.required ?? [],
		users: previewConfigs.users.secrets?.required ?? []
	}
	const previewSecretEnvironment = Object.fromEntries(
		[...new Set([...requiredPreviewSecrets.auth, ...requiredPreviewSecrets.users])].map((name) => [
			name === 'DATABASE_URL' ? 'STAGING_DATABASE_URL' : name,
			name === 'DATABASE_URL' ? previewDatabaseUrl : verificationSecretValue(name)
		])
	)
	const previewSecretPreparation = await run({
		name: 'write-preview-secrets',
		executable: 'node',
		args: ['scripts/write-cloudflare-preview-secrets.mjs', previewSecretDirectory],
		cwd: project,
		logPath: join(project, 'write-preview-secrets.log'),
		extraEnv: previewSecretEnvironment
	})
	const previewSecretFiles: Partial<Record<string, string>> = {
		auth: join(previewSecretDirectory, 'auth.json'),
		...(requiredPreviewSecrets.users.length > 0
			? { users: join(previewSecretDirectory, 'users.json') }
			: {})
	}
	const previewSecretValues: Partial<Record<'auth' | 'users', Record<string, string>>> = {}
	for (const name of ['auth', 'users'] as const) {
		const file = previewSecretFiles[name]
		if (!file) continue
		const values = JSON.parse(await readFile(file, 'utf8')) as Record<string, string>
		previewSecretValues[name] = values
		if (
			JSON.stringify(Object.keys(values).sort()) !==
			JSON.stringify(requiredPreviewSecrets[name].sort())
		)
			throw new Error(`${name} preview secrets file does not match required secrets`)
	}
	const databaseEvidence = assertPreviewDatabaseIsolation({
		config,
		production: configs,
		preview: previewConfigs,
		alias: args.stagingAlias,
		previewDatabaseName,
		previewDatabaseId,
		previewDatabaseUrl,
		previewSecretValues
	})

	const webPackage = JSON.parse(await readFile(join(project, 'apps/web/package.json'), 'utf8')) as {
		name: string
	}
	await rm(join(project, 'apps/web/.svelte-kit'), { recursive: true, force: true })
	const cleanWebBuildEnvironment = {
		...(hasMarketing ? { PUBLIC_APP_URL: webOrigin } : {}),
		...(config.choices.auth.includes('emailOTP')
			? { PUBLIC_TURNSTILE_SITE_KEY: '1x00000000000000000000AA' }
			: {})
	}
	const cleanWebBuild = await run({
		name: 'clean-preview-web-build',
		executable: 'corepack',
		args: [
			`pnpm@${PNPM_VERSION}`,
			'turbo',
			'run',
			'build',
			`--filter=${webPackage.name}`,
			'--force'
		],
		cwd: project,
		logPath: join(project, 'clean-preview-web-build.log'),
		extraEnv: cleanWebBuildEnvironment
	})

	let cleanMarketingBuild: CommandResult | undefined
	if (hasMarketing) {
		const marketingPackage = JSON.parse(
			await readFile(join(project, MARKETING_WORKER.directory, 'package.json'), 'utf8')
		) as { name: string }
		await rm(join(project, MARKETING_WORKER.directory, 'dist'), { recursive: true, force: true })
		cleanMarketingBuild = await run({
			name: 'clean-preview-marketing-build',
			executable: 'corepack',
			args: [
				`pnpm@${PNPM_VERSION}`,
				'turbo',
				'run',
				'build',
				`--filter=${marketingPackage.name}`,
				'--force'
			],
			cwd: project,
			logPath: join(project, 'clean-preview-marketing-build.log'),
			extraEnv: {
				PUBLIC_MARKETING_URL: marketingOrigin ?? '',
				PUBLIC_APP_URL: webOrigin
			}
		})
	}

	const previewDryRuns: Partial<Record<WorkerName, CommandResult>> = {}
	for (const worker of workers) {
		const secretsFile = previewSecretFiles[worker.name]
		previewDryRuns[worker.name] = await run({
			name: `preview-wrangler-dry-run-${worker.name}`,
			executable: 'corepack',
			args: [
				`pnpm@${PNPM_VERSION}`,
				'--dir',
				worker.directory,
				'exec',
				'wrangler',
				'deploy',
				'--config',
				'wrangler.staging.jsonc',
				...(secretsFile ? ['--secrets-file', secretsFile] : []),
				'--dry-run',
				'--outdir',
				'.wrangler/verify-preview-dry-run'
			],
			cwd: project,
			logPath: join(project, `wrangler-${worker.name}-preview-dry-run.log`)
		})
	}
	const cleanWebDryRun = previewDryRuns.web
	if (!cleanWebDryRun) throw new Error('clean preview web dry-run did not execute')
	const cleanMarketingDryRun = previewDryRuns.marketing
	if (cleanMarketingBuild && !cleanMarketingDryRun)
		throw new Error('clean preview marketing dry-run did not execute')
	await rm(previewSecretDirectory, { recursive: true, force: true })

	const localExample = await readFile(join(project, '.env.example'), 'utf8')
	if (/^PUBLIC_(?:API|AUTH|USERS)_URL=/m.test(localExample))
		throw new Error('.env.example contains a direct-service public URL')
	const productionExample = await readFile(join(project, '.env.cloudflare.example'), 'utf8')
	if (/SECRET|TOKEN|API_KEY|PASSWORD/.test(productionExample))
		throw new Error('.env.cloudflare.example contains a secret field')

	const previewWorkerNames = workers.map((worker) => previewConfigs[worker.name].name)
	if (
		previewWorkerNames.some((name) => Object.values(configs).some((config) => config.name === name))
	)
		throw new Error('preview cleanup inventory includes a production Worker')
	const previewRoutes = workers.flatMap(
		(worker) => previewConfigs[worker.name].routes?.map(({ pattern }) => pattern) ?? []
	)
	const evidence = {
		project: '.',
		workspaceChecks: workspaceChecks.map(({ command }) => command),
		freshWorkspaceInputsUnchanged: true,
		database: databaseEvidence,
		inventory: Object.fromEntries(
			workers.map((worker) => [worker.name, inventory(configs[worker.name])])
		),
		generatedTypes,
		dryRuns: Object.fromEntries(
			Object.entries(dryRuns).map(([name, result]) => [
				name,
				{
					command: result.command,
					bundleProved: /Total Upload|dry-run|--dry-run/i.test(result.output)
				}
			])
		),
		preview: {
			alias: args.stagingAlias,
			aliases: {
				pr: args.stagingAlias,
				manual: manualAlias,
				maximumLength: 48,
				rejected: rejectedAliases
			},
			lifecycle: {
				prCleanupTrigger: 'pull_request.closed',
				manualCleanupTrigger: 'workflow_dispatch.inputs.alias',
				manualCleanupInvocation: 'gh workflow run cleanup-staging.yml -f alias=<canonical alias>',
				trustedCleanupRef: '${{ github.event.repository.default_branch }}',
				prControlledCleanupCode: false,
				sharedConcurrencyAlias: true
			},
			deployScripts: previewDeployScripts,
			apiOrigin,
			webOrigin,
			preparationCommand: previewPreparation.command,
			failClosedCommand: failClosed.command,
			ingressPrerequisites: {
				checkedBeforeProvisioning: true,
				sharedWildcardDns: [`*.${previewWebDomain}`, `*.${previewApiDomain}`],
				remoteCheckPerformedByVerifier: false
			},
			secretBootstrap: {
				preparationCommand: previewSecretPreparation.command,
				workers: Object.keys(previewSecretFiles),
				secretsIncludedInInitialDryRun: true,
				secretPutDeployments: false
			},
			cleanWebDeploy: {
				removedOutput: 'apps/web/.svelte-kit',
				buildCommand: cleanWebBuild.command,
				dryRunCommand: cleanWebDryRun.command,
				turnstileSiteKeyRequiredBeforeProvisioning:
					config.choices.auth.includes('emailOTP'),
				turnstileSiteKeyForwarded: config.choices.auth.includes('emailOTP')
			},
			inventory: Object.fromEntries(
				workers.map((worker) => [worker.name, inventory(previewConfigs[worker.name])])
			),
			marketingDeploy: cleanMarketingBuild
				? {
						origin: marketingOrigin,
						buildCommand: cleanMarketingBuild.command,
						dryRunCommand: cleanMarketingDryRun?.command
					}
				: null,
			dryRuns: Object.fromEntries(
				Object.entries(previewDryRuns).map(([name, result]) => [
					name,
					{
						command: result.command,
						bundleProved: /Total Upload|dry-run|--dry-run/i.test(result.output)
					}
				])
			),
			cleanupTargets: {
				workers: previewWorkerNames,
				routes: previewRoutes,
				sharedWildcardDnsPreserved: true,
				database:
					databaseEvidence.kind === 'd1'
						? { kind: 'd1', databaseName: databaseEvidence.previewDatabaseName }
						: { kind: 'neon', branchName: databaseEvidence.previewBranchName },
				productionExcluded: true,
				sourceBranchDeletion: false
			}
		},
		privatePublicTriggers: { auth: [], users: [] },
		remoteResourcesCreated: false
	}
	await writeSanitizedArtifact({
		path: join(project, 'evidence.json'),
		content: `${JSON.stringify(evidence, null, 2)}\n`,
		roots: [project]
	})
	console.log(JSON.stringify(evidence, null, 2))
}

if (import.meta.main) {
	main().catch((error: unknown) => {
		console.error(error instanceof Error ? error.message : String(error))
		process.exitCode = 1
	})
}
